FROM python:latest
RUN pip install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node
ENTRYPOINT flatpak-node-generator npm /usr/src/frontier/package-lock.json -o /usr/src/frontier/node-sources.json
