FROM python:latest
RUN pip install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node
ENTRYPOINT flatpak-node-generator pnpm /usr/src/frontier/pnpm-lock.yaml -o /usr/src/frontier/node-sources.json
